# Generated by Django 4.2.11 on 2024-03-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_employee_created_at_employee_entered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='exited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
