# Generated by Django 4.2.11 on 2024-03-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_employee_exited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='entered_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='exited_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
